#!/usr/bin/env bash
# This is a script for transferring files
# from local client to server

if [ $# -ne 4 ]; then
 echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
exit 1

fi
FILE=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY=$4

scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE" "$USERNAME"@"$SERVER_IP":~/
