#!/usr/bin/env bash
# display hours(0-12) and minutes(1-59)
hour=0
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	minutes=1
	while [ $minutes -lt 60 ]
	do
		echo $minutes
		minutes=$((minutes+1))
	done
	hour=$((hour+1))
done
